Our Nerual network architecture will be as follows..
--Input will have three variables with 4 Feaures
--Will have a our filter which will have same no of channel as Input and hence our Filter will be (4,3)
--Three Bias values will be available as we have three input
--Have one hidden layer
--Activation Function is being assumed as Sigmoid
--Outputs have been clarified and Response will be compared with Output to calculate the Error
--Weights for Kernel and Hidden layer will be updated based on error to minimise the error 

This section explains the Input value which is is matrix. We need to set the matrix element (1,1), (1,2), (2.1),(2,3), (2,4), (3,2) and (3,4) to 1. This input will then be passed through our kernel.
Note: Here we have three Input and their 4 feature values. So the matrix size is (3,4)

Back Propagation has following phases and they are
-Initialisation of weights for Kernel and Hidden filters
    -Initialise all the weights for all the neurals to some dandom values    
-Feed Forward from Input layer to output of layers
    -Propagate input to hidden and output layers
    -Calculate input to hidden layer and output of hidden layers
    -Calculate input to the Output layer
-Backprogataion of Errors
    -Calculate error for output layers neurons
-Updation of weights and biases

In [ ]:
import numpy as np
import pandas as pd
import scipy as sc
import plotly as pt
import matplotlib as mp
import sys as sy
import random as rd
from scipy.stats import logistic as lg

In [2]:
row =3
column =4
InputValue = np.zeros(shape=(row,column))
Input_matrix = np.matrix(np.array(InputValue))

print(Input_matrix)
Input_matrix[0,0] =1
Input_matrix[0,2] =1
Input_matrix[1,0] =1
Input_matrix[1,2] =1
Input_matrix[1,3] =1
Input_matrix[2,1] =1
Input_matrix[2,3] =1
print("Input Is",Input_matrix)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Input Is [[1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]]


This section explains our kernel with random values as weightage. Initialize weights and biases with random values. Note: Here the Bias has three value which is alligned with 3 Input.

In [3]:
## Defining the kernel weights
wh = np.random.rand(4,3)
print(wh)
wh_matrix = np.matrix(np.array(wh))
print("Filter Weights:", wh_matrix)

## Now defining the bias values
bias = np.random.rand(1,3)
bias_matrix = np.matrix(np.array(bias))
print("Bias Values:", bias_matrix)


[[0.2579583  0.06285557 0.42894311]
 [0.37526935 0.54573107 0.98683106]
 [0.91736504 0.0356562  0.15877861]
 [0.95315662 0.75385089 0.20946059]]
Filter Weights: [[0.2579583  0.06285557 0.42894311]
 [0.37526935 0.54573107 0.98683106]
 [0.91736504 0.0356562  0.15877861]
 [0.95315662 0.75385089 0.20946059]]
Bias Values: [[0.67667588 0.36880179 0.78954195]]


Following section calculate input of Hidden layer. We have Input matrix, then Kernel and so Output from kernel will be dot product of Input and Kernel matrix. Then bias will be added with that.

In [4]:
## here we are doing dot product of two matrix
Output_Kernel = np.dot(Input_matrix,wh_matrix)
print("Output of Kernel:", Output_Kernel)
Output_Kernel_Bias = np.add(Output_Kernel,bias_matrix)
print("Output of Kernel after Bias Addition:", Output_Kernel_Bias)

Output of Kernel: [[1.17532334 0.09851177 0.58772172]
 [2.12847996 0.85236266 0.79718232]
 [1.32842597 1.29958196 1.19629165]]
Output of Kernel after Bias Addition: [[1.85199922 0.46731356 1.37726367]
 [2.80515584 1.22116445 1.58672427]
 [2.00510185 1.66838375 1.9858336 ]]


In [5]:
## This function is meant for sigmoid derivative
def sigmoid_mod(x):
    return 1 / (1 + np.exp(-x))

Our activation function is taken as sigmoid one. So all input to our hidden network will be going through sigmoid activation function to have output.

In [6]:
Input_Hidden_layer = Output_Kernel_Bias
##Output_hidden_layer = lg.cdf(Input_Hidden_layer)
Output_hidden_layer = sigmoid_mod(Input_Hidden_layer)  ### applying sigmoid


print("Output of Hidden Layer:", Output_hidden_layer)

Output of Hidden Layer: [[0.86436166 0.61474771 0.79855117]
 [0.9429538  0.77226841 0.83015473]
 [0.8813317  0.84136021 0.87930166]]


This section first defines the weights for hindden layer and then bias fo hidden layer. Hiddden layer has activation function and output from activation function is a matrix is (3,3). So our weights for hidden layer will have only 3 variables with one feature. We will take these weights as random ones.

In [7]:
###Defining the weights for hidden layer
wout = np.random.rand(3,1)
wout_matrix = np.matrix(np.array(wout))
print("Hidden Layer Weights:", wout_matrix)
##defining the bias for hidden layer
wout_bias = np.random.rand(1,1)
print("Hidden Layer Bias Value:", wout_bias)


Hidden Layer Weights: [[0.75179991]
 [0.0161383 ]
 [0.70208934]]
Hidden Layer Bias Value: [[0.6218857]]


This section explains how the hidden layer neural network applies weights and then gets influenced by bias at the hidden layer.

In [8]:
Output_hidden_layer_after_weight = np.dot(Output_hidden_layer,wout_matrix)
print("Hidden layer output after weight:", Output_hidden_layer_after_weight)

Output_hidden_layer_after_bias = np.add(Output_hidden_layer_after_weight,wout_bias)
print("Hidden layer output after Bias:", Output_hidden_layer_after_bias)


Hidden layer output after weight: [[1.22040227]
 [1.30421847]
 [1.29351154]]
Hidden layer output after Bias: [[1.84228797]
 [1.92610417]
 [1.91539724]]


Our expected output is a having three input value as 1,1,0.

In [9]:
rowOut =3
columnOut =1
OutputValue = np.zeros(shape=(rowOut,columnOut))
OutputValue_matrix = np.matrix(np.array(OutputValue))
OutputValue_matrix[0,0] = 1
OutputValue_matrix[1,0] = 1
print("Expected Output:", OutputValue_matrix)


Expected Output: [[1.]
 [1.]
 [0.]]


Lets now calculate the error. Error will be Final output - Expected Output. Back Propagation is the way the weights are trained into each of the layers and kernel. Actually these errors are then passed back from putput to hidden layer and then to kernel as similar to passing the blame.

In [10]:
print(Output_hidden_layer_after_bias)
print(OutputValue_matrix)
Gradient_Error_Value_1st_Iter = np.subtract(OutputValue_matrix,Output_hidden_layer_after_bias)
print("Error Term for Hidden Layer:", Gradient_Error_Value_1st_Iter)


[[1.84228797]
 [1.92610417]
 [1.91539724]]
[[1.]
 [1.]
 [0.]]
Error Term for Hidden Layer: [[-0.84228797]
 [-0.92610417]
 [-1.91539724]]


Backpropagation is splitted into two section and they are -Transfer Derivative and -Error Backpropagation. The hidden layer has sigmoid activation function and hence and the derivative of the same will be as follows. Aim is to adjust each weight in the network in proportion to how much it contributes to overall error.

In [11]:
## This function is meant for sigmoid derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [12]:
k = sigmoid(Gradient_Error_Value_1st_Iter)
#print(k)

kky = np.random.rand(3,1)

wout_kky = np.matrix(np.array(kky))
wout_kky[0,0] = 0.21
wout_kky[1,0] = 0.20
wout_kky[2,0] = -0.79
mk = sigmoid(wout_kky)
print(mk)

[[0.55230791]
 [0.549834  ]
 [0.31216867]]


We will now calculate the Output slope. Slope for sigmoid activation function will be calculated as value(1-value).

In [13]:
Output_slope_delta = np.subtract(Output_hidden_layer_after_bias,1)
#Output_slope = np.dot(Output_slope_delta,Output_hidden_layer_after_bias) ## output slope calculated here
rowOut =3
columnOut =1
Output_slope = np.zeros(shape=(rowOut,columnOut))
Output_slope_matrix = np.matrix(np.array(Output_slope))

#m = value * value1
#v = round(m,2)
#Output_slope_matrix[0,0] = v
num = 0
for num in range(0,3):     #to iterate between 10 to 20
    Output_slope_matrix[num,0] = round((Output_hidden_layer_after_bias[num,0] * Output_slope_delta[num,0]) ,2)

    
print("Output Slope:",Output_slope_matrix)
print("Output_hidden_layer_after_bias:",Output_hidden_layer_after_bias)      
print("Output_slope_delta:",Output_slope_delta) 
### Now we need to multiply the slope and delta output. Delta output will be driven by error which is the 
rowOut =3
columnOut =1
delta_output = np.zeros(shape=(rowOut,columnOut))
delta_output_m = np.matrix(np.array(Output_slope))

for num in range(0,3):     #to iterate between 10 to 20
    delta_output_m[num,0] = round((Output_slope_matrix[num,0] * Gradient_Error_Value_1st_Iter[num,0]) ,2)
    
print("Output_slope_matrix:",Output_slope_matrix) 
print("Gradient_Error_Value_1st_Iter:",Gradient_Error_Value_1st_Iter) 
print("delta_output_m",delta_output_m) 

Output Slope: [[1.55]
 [1.78]
 [1.75]]
Output_hidden_layer_after_bias: [[1.84228797]
 [1.92610417]
 [1.91539724]]
Output_slope_delta: [[0.84228797]
 [0.92610417]
 [0.91539724]]
Output_slope_matrix: [[1.55]
 [1.78]
 [1.75]]
Gradient_Error_Value_1st_Iter: [[-0.84228797]
 [-0.92610417]
 [-1.91539724]]
delta_output_m [[-1.31]
 [-1.65]
 [-3.35]]


We now have calculated delta output and next task is to calculate error at hidden layer, slope at hidden layer and then delta at hidden layer.

In [14]:
### First step is to calculate error at hidden layer
wout_matrix_T = np.transpose(wout_matrix)
Error_Hidden_layer = np.dot(delta_output_m,wout_matrix_T)
print("Error_Hidden_layer",Error_Hidden_layer) 
### Note here have taken the output of the hidden layer and this output is before applying the bias and weights. So this is again as part
## of back progation we are doing sigmoid
Slope_hidden_layer = sigmoid(Output_hidden_layer)

print("Slope_hidden_layer",Output_hidden_layer_after_weight) 
## we will now calculate the derivative which is multipliction of slope and error
derivative_hiddenlayer = Slope_hidden_layer * Error_Hidden_layer
print("derivative_hiddenlayer",derivative_hiddenlayer) 


Error_Hidden_layer [[-0.98485788 -0.02114117 -0.91973704]
 [-1.24046985 -0.02662819 -1.15844742]
 [-2.51852969 -0.0540633  -2.3519993 ]]
Slope_hidden_layer [[1.22040227]
 [1.30421847]
 [1.29351154]]
derivative_hiddenlayer [[-3.23495156 -0.06944217 -3.02104988]
 [-3.31116667 -0.07107822 -3.09222548]
 [-3.34295968 -0.0717607  -3.12191628]]


Compute delta at hidden layer and learning_rate is asssumed as 0.1

In [15]:
learning_rate =0.1
Output_hidden_layer_after_weight_T = np.transpose(Output_hidden_layer_after_weight)
## we are calculating the hidden layer weights now with back propagation
wout_matrix_bp = wout_matrix + np.dot(Output_hidden_layer_after_weight_T,derivative_hiddenlayer) * learning_rate
print("wout_matrix_bp",wout_matrix_bp) 
# we are now calculating the initial kernel filter weights
Input_matrix_T = np.transpose(Input_matrix)
wh_matrix_bp = wh_matrix + np.dot(Input_matrix_T,derivative_hiddenlayer) * learning_rate
print("wout_matrix_bp",wh_matrix_bp) 


wout_matrix_bp [[-0.50725848  0.72477269 -0.42400694]
 [-1.24292009 -0.01088892 -1.15966854]
 [-0.55696904  0.67506212 -0.4737175 ]]
wout_matrix_bp [[-0.39665352  0.04880353 -0.18238442]
 [ 0.04097338  0.538555    0.67463943]
 [ 0.26275322  0.02160416 -0.45254892]
 [ 0.28774399  0.739567   -0.41195358]]


This section explains our intial randomly assigned weights and newly calculated weights after backpropagation.

In [16]:
print("Initial Weights of Filter:", wh_matrix)
print("Revised Weights of Filter After Back Propagation:", wout_matrix_bp)

print("Initial Weights of Hidden Layer:", wh_matrix)
print("Revised Weights of Hidden Layer After Back Propagation:", wh_matrix_bp)

Initial Weights of Filter: [[0.2579583  0.06285557 0.42894311]
 [0.37526935 0.54573107 0.98683106]
 [0.91736504 0.0356562  0.15877861]
 [0.95315662 0.75385089 0.20946059]]
Revised Weights of Filter After Back Propagation: [[-0.50725848  0.72477269 -0.42400694]
 [-1.24292009 -0.01088892 -1.15966854]
 [-0.55696904  0.67506212 -0.4737175 ]]
Initial Weights of Hidden Layer: [[0.2579583  0.06285557 0.42894311]
 [0.37526935 0.54573107 0.98683106]
 [0.91736504 0.0356562  0.15877861]
 [0.95315662 0.75385089 0.20946059]]
Revised Weights of Hidden Layer After Back Propagation: [[-0.39665352  0.04880353 -0.18238442]
 [ 0.04097338  0.538555    0.67463943]
 [ 0.26275322  0.02160416 -0.45254892]
 [ 0.28774399  0.739567   -0.41195358]]
